---
title: "Spawning"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_depth: 3
    toc_float:
      collapsed: FALSE
    code_folding: show
    number_sections: TRUE
---

    # SET-UP
```{r markdwon, echo=F}
library(knitr)
opts_chunk$set(echo = T, collapse = T, fig.align = "center", fig.width = 9, fig.height = 6, message=F, warning=F)
options(width = 200)
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

my.year <- 2024 # maximum year to extract data
year_to_plot= (my.year-5) : my.year

```    

```{r code=readLines(paste0('R/',my.year,'/0.0_settings.R'))}

```
  

```{r settings}
new=T
N=100
load(file=paste0("data/",my.year,"/DEP.RData"))
load(file=paste0("data/",my.year,"/eggt1.RData"))
dat=eggt1

```

# Read 

```{r read spawn, message = F}
#prop_spawn(year,year=year, dat = egg, cv = T) # dat is used to calculate median date and in split with trajet.

date.med <- eggt1 %>%  filter(year !=1979) %>%
  ungroup() %>%
  group_by(year) %>%
  dplyr::summarize(
    date.med = round(median(doy, na.rm = T)),
    mindoy = min(doy, na.rm = T),
    maxdoy = max(doy, na.rm = T)
  )

date.med <- date.med %>% mutate(date.med = ifelse(year == 1979, 166, date.med)) # from Ouellet et al. 1987
date.med <- as.data.frame(date.med)

bio <- get.bio(species = "maquereau", user = my.env$bio.username, password = my.env$bio.password)

    
      bio <- bio %>% mutate(doy = as.numeric(format(as.Date(paste(year, month, day, sep = "/"), format = "%Y/%m/%d"), format = "%j"))) %>%
        dplyr::filter(
          !is.na(weight), !is.na(wgonad), !is.na(doy),
          weight > 0, weight > wgonad, matur != 0, nafo %in% c("4T", "4V", "4W")
        ) 
    
      
bio %<>% mutate(gsi = (wgonad / weight) * 100)

#remove outliers
df <- bio %>%
  dplyr::filter(!is.na(gsi), matur > 4, year > 1978, !(gsi > 5 & doy > 250), !(gsi > 10 & doy > 200 & year %in% c(1994, 1999, 2018, 2019, 2020)), !(year == 1999 & matur > 6 & nafo == "4V"), !(nafo!="4T" & matur > 6), !(nafo!="4T" & matur>6 & month >7), length.frozen > 0.2, weight > 0.03, gsi < 40)  %>%  
  group_by(agef) %>% filter(weight>quantile(weight,0.0001), weight<quantile(weight,0.9999))%>% 
  arrange(year)


df <- df %>%
  arrange(year) %>%
  mutate(year = as.numeric(as.character(year))) %>%  filter(!is.na(gsi), !is.na(doy), !is.na(year)) %>% mutate(maturcat = ifelse(!is.na(matur) & matur == 6, "6",                                                                                                                                 ifelse(is.na(matur), "other", "other"))) %>%  ungroup()



df<- df %>%  mutate(gsi=gsi/100)
```

## CHECKS {.tabset} 

### Check for outliers
```{r check outliers, message = F}
df %>% filter(year %in% year_to_plot) %>% ggplot(aes(x=doy, y=gsi)) +geom_point(aes(col=maturcat)) + facet_wrap(~year) + scale_color_manual(values = c("green3", "grey")) 

```


### Model {.tabset}
```{r spawn2, message = F}

#evaluate starting values

if(new){
start.val <- nls.multstart::nls_multstart(gsi ~ SSlogis(doy, Asym, xmid, scal),
                                          data = df,
                                          start_lower = c(Asym =0, xmid = min(df$doy), scal = -100),
                                          start_upper = c(Asym = 1, xmid = max(df$doy), scal = 100),
                                          iter = 500,
                                          supp_errors = "Y"
)


nlme.fixAR <- nlme(gsi ~ SSlogis(doy, Asym, xmid, scal),
  data = df,
  fixed = Asym + xmid + scal ~ 1,
  start = coefficients(start.val),
  correlation = corAR1(),
  random = Asym + xmid + scal ~ 1 | year
)

nlme_coefAR = as_tibble(coef(nlme.fixAR), rownames = 'year')

#keep starting values in case of needed for update
#save(nlme.fixAR,start.val,df, nlme_coefAR, file = paste0("results/", my.year,"/spawning/nlmeAR", my.year,".RData"))
}# else{#load(paste0("results/", my.year,"/spawning/nlmeAR", my.year,".RData"))}

predtimes <- expand_grid(year = unique(df$year), doy = seq(0.5, 364.5)) # doy aligned to calculate probability at doy


nlme.fixpredsAR1 <- predtimes %>%
  mutate(fitted =predict(nlme.fixAR, newdata = predtimes,interval = 'confidence')) %>%
  group_by(year) %>%
  mutate(
    slope = c(diff(fitted, lag = 1), NA),
    prob = slope / sum(slope, na.rm = T)
  ) %>%
  filter(!is.na(prob)) %>%
  mutate(
    probcum0025 = cumsum(prob),
    #probcum9725 = rev(cumsum(rev(prob))),
    doy = ceiling(doy)
  ) # get back the real doy

```
 


 
#### Check
```{r spawvalid1, message = F}
valid<- data.frame(resid=residuals(nlme.fixAR , type="normalized"), mu=fitted(nlme.fixAR), obs=df$gsi, year=df$year)

h<- ggplot(valid, aes(x=mu, y=resid))+geom_point(col="grey35", size=0.5) +theme_few() + geom_hline(yintercept=0, col="red", lty=2)
f<- ggplot(valid, aes(x=df$gsi, y=mu))+geom_point(col="grey35", size=0.5)+theme_few() +geom_abline(slope=1, intercept=0, col="red", lty=2)+ geom_smooth(method="lm")

hEN <-  h+ ylab("Pearson's residuals") + xlab("Fitted values")

fEN <-  f+ ylab("Fitted values") + xlab("Observed values")

ggarrange(hEN, fEN, ncol=2)


h<- ggplot(valid, aes(x=mu, y=resid))+geom_point(col="grey35", size=0.5) +theme_few() + facet_wrap( ~ year) +geom_hline(yintercept=0, col="red", lty=2)
f<- ggplot(valid, aes(x=df$gsi, y=mu))+geom_point(col="grey35", size=0.5)+theme_few() + facet_wrap( ~ year) +geom_abline(slope=1, intercept=0, col="red", lty=2)+ geom_smooth(method="lm")

hEN <-  h+ ylab("Pearson's residuals") + xlab("Fitted values")

ggarrange(hEN, fEN, ncol=2)
```
